/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type UniversityTier = typeof UniversityTier[keyof typeof UniversityTier];


export const UniversityTier = {
  safe: 'safe',
  target: 'target',
  reach: 'reach',
} as const;

export interface University {
  id: string;
  name: string;
  city: string;
  country: string;
  countryCode: string;
  region: string;
  type: string;
  rank: number;
  tuition: number;
  livingCost: number;
  acceptanceRate: number;
  fitScore: number;
  tier: UniversityTier;
  fields: string[];
  languages: string[];
  applicationUrl: string;
  logo: string;
  image: string;
  highlights: string[];
}

export type StudentProfileInputDegreeLevel = typeof StudentProfileInputDegreeLevel[keyof typeof StudentProfileInputDegreeLevel];


export const StudentProfileInputDegreeLevel = {
  'Bachelor\'s': 'Bachelor\'s',
  'Master\'s': 'Master\'s',
  PhD: 'PhD',
} as const;

export type StudentProfileInputGradeSystem = typeof StudentProfileInputGradeSystem[keyof typeof StudentProfileInputGradeSystem];


export const StudentProfileInputGradeSystem = {
  US_GPA: 'US GPA',
  UK_Honours: 'UK Honours',
  ECTS: 'ECTS',
  Bavarian: 'Bavarian',
  Percentage: 'Percentage',
} as const;

export type StudentProfileInputEnglishTest = typeof StudentProfileInputEnglishTest[keyof typeof StudentProfileInputEnglishTest];


export const StudentProfileInputEnglishTest = {
  IELTS: 'IELTS',
  TOEFL: 'TOEFL',
} as const;

export type StudentProfileInputCurrency = typeof StudentProfileInputCurrency[keyof typeof StudentProfileInputCurrency];


export const StudentProfileInputCurrency = {
  EUR: 'EUR',
  GBP: 'GBP',
  CHF: 'CHF',
} as const;

export interface StudentProfileInput {
  degreeLevel: StudentProfileInputDegreeLevel;
  field: string;
  grade: number;
  gradeSystem: StudentProfileInputGradeSystem;
  englishScore: number;
  englishTest?: StudentProfileInputEnglishTest;
  budget: number;
  currency?: StudentProfileInputCurrency;
  experienceYears: number;
  region: string;
  gre?: number;
  prerequisiteTopics?: string[];
}

export interface MatchSummary {
  profileStrength: number;
  totalMatches: number;
  safeCount: number;
  targetCount: number;
  reachCount: number;
  topInsight: string;
}

export interface MatchResponse {
  matches: University[];
  summary: MatchSummary;
}

export type GradeConversionInputFromSystem = typeof GradeConversionInputFromSystem[keyof typeof GradeConversionInputFromSystem];


export const GradeConversionInputFromSystem = {
  US_GPA: 'US GPA',
  UK_Honours: 'UK Honours',
  ECTS: 'ECTS',
  Bavarian: 'Bavarian',
  Percentage: 'Percentage',
} as const;

export type GradeConversionInputToSystem = typeof GradeConversionInputToSystem[keyof typeof GradeConversionInputToSystem];


export const GradeConversionInputToSystem = {
  US_GPA: 'US GPA',
  UK_Honours: 'UK Honours',
  ECTS: 'ECTS',
  Bavarian: 'Bavarian',
  Percentage: 'Percentage',
} as const;

export interface GradeConversionInput {
  value: number;
  fromSystem: GradeConversionInputFromSystem;
  toSystem: GradeConversionInputToSystem;
}

export interface GradeConversion {
  value: number;
  label: string;
  explanation: string;
  scale: string;
}

export interface BridgeCourse {
  id: string;
  title: string;
  provider: string;
  topic: string;
  ects: number;
  duration: string;
  url: string;
  level: string;
}

export interface PlannerWorkspaceInput {
  selectedIds: string[];
  visaTasks: string[];
  auditFiles: string[];
  sopField: string;
  sopInterest: string;
  sopGoal: string;
  resumeText: string;
  ectsTopics: string[];
  syllabusFiles: string[];
}

export type PlannerWorkspace = PlannerWorkspaceInput & {
  updatedAt: string;
};

export type ListUniversitiesParams = {
search?: string;
country?: string;
region?: string;
degreeLevel?: ListUniversitiesDegreeLevel;
field?: string;
maxTuition?: number;
tier?: ListUniversitiesTier;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};

export type ListUniversitiesDegreeLevel = typeof ListUniversitiesDegreeLevel[keyof typeof ListUniversitiesDegreeLevel];


export const ListUniversitiesDegreeLevel = {
  'Bachelor\'s': 'Bachelor\'s',
  'Master\'s': 'Master\'s',
  PhD: 'PhD',
} as const;

export type ListUniversitiesTier = typeof ListUniversitiesTier[keyof typeof ListUniversitiesTier];


export const ListUniversitiesTier = {
  safe: 'safe',
  target: 'target',
  reach: 'reach',
} as const;

export type ListBridgeCoursesParams = {
topic?: string;
};

