/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BridgeCourse,
  GradeConversion,
  GradeConversionInput,
  HealthStatus,
  ListBridgeCoursesParams,
  ListUniversitiesParams,
  MatchResponse,
  PlannerWorkspace,
  PlannerWorkspaceInput,
  StudentProfileInput,
  University
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * Returns server health status
 * @summary Health check
 */
export const healthCheck = async ( options?: Parameters<typeof customFetch>[1]): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getListUniversitiesUrl = (params?: ListUniversitiesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/universities?${stringifiedParams}` : `/api/universities`
}

/**
 * Returns a filterable catalog of universities with admissions fit signals.
 * @summary List European universities
 */
export const listUniversities = async (params?: ListUniversitiesParams, options?: Parameters<typeof customFetch>[1]): Promise<University[]> => {

  return customFetch<University[]>(getListUniversitiesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListUniversitiesQueryKey = (params?: ListUniversitiesParams,) => {
    return [
    `/api/universities`, ...(params ? [params] : [])
    ] as const;
    }


export const getListUniversitiesQueryOptions = <TData = Awaited<ReturnType<typeof listUniversities>>, TError = ErrorType<unknown>>(params?: ListUniversitiesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listUniversities>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUniversitiesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUniversities>>> = ({ signal }) => listUniversities(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUniversities>>, TError, TData> & { queryKey: QueryKey }
}

export type ListUniversitiesQueryResult = NonNullable<Awaited<ReturnType<typeof listUniversities>>>
export type ListUniversitiesQueryError = ErrorType<unknown>


/**
 * @summary List European universities
 */

export function useListUniversities<TData = Awaited<ReturnType<typeof listUniversities>>, TError = ErrorType<unknown>>(
 params?: ListUniversitiesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listUniversities>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListUniversitiesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetUniversityUrl = (universityId: string,) => {




  return `/api/universities/${universityId}`
}

/**
 * @summary Get a university profile
 */
export const getUniversity = async (universityId: string, options?: Parameters<typeof customFetch>[1]): Promise<University> => {

  return customFetch<University>(getGetUniversityUrl(universityId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUniversityQueryKey = (universityId: string,) => {
    return [
    `/api/universities/${universityId}`
    ] as const;
    }


export const getGetUniversityQueryOptions = <TData = Awaited<ReturnType<typeof getUniversity>>, TError = ErrorType<void>>(universityId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUniversity>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUniversityQueryKey(universityId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUniversity>>> = ({ signal }) => getUniversity(universityId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: universityId !== null && universityId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUniversity>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUniversityQueryResult = NonNullable<Awaited<ReturnType<typeof getUniversity>>>
export type GetUniversityQueryError = ErrorType<void>


/**
 * @summary Get a university profile
 */

export function useGetUniversity<TData = Awaited<ReturnType<typeof getUniversity>>, TError = ErrorType<void>>(
 universityId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUniversity>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUniversityQueryOptions(universityId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getMatchUniversitiesUrl = () => {




  return `/api/counselor/match`
}

/**
 * @summary Match a student profile to universities
 */
export const matchUniversities = async (studentProfileInput: StudentProfileInput, options?: Parameters<typeof customFetch>[1]): Promise<MatchResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<MatchResponse>(getMatchUniversitiesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(studentProfileInput)
  }
);}





export const getMatchUniversitiesMutationKey = () => ['matchUniversities'] as const;

export const getMatchUniversitiesMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof matchUniversities>>, TError,MatchUniversitiesMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof matchUniversities>>, TError,MatchUniversitiesMutationVariables, TContext> => {

const mutationKey = getMatchUniversitiesMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof matchUniversities>>, MatchUniversitiesMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  matchUniversities(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MatchUniversitiesMutationResult = NonNullable<Awaited<ReturnType<typeof matchUniversities>>>
    export type MatchUniversitiesMutationBody = BodyType<StudentProfileInput>
    export type MatchUniversitiesMutationError = ErrorType<unknown>
    export type MatchUniversitiesMutationVariables = {data: BodyType<StudentProfileInput>}

    /**
 * @summary Match a student profile to universities
 */
export const useMatchUniversities = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof matchUniversities>>, TError,MatchUniversitiesMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof matchUniversities>>,
        TError,
        MatchUniversitiesMutationVariables,
        TContext
      > => {
      return useMutation(getMatchUniversitiesMutationOptions(options));
    }

export const getConvertGradeUrl = () => {




  return `/api/counselor/convert-grade`
}

/**
 * @summary Convert a grade between common European and global systems
 */
export const convertGrade = async (gradeConversionInput: GradeConversionInput, options?: Parameters<typeof customFetch>[1]): Promise<GradeConversion> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<GradeConversion>(getConvertGradeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(gradeConversionInput)
  }
);}





export const getConvertGradeMutationKey = () => ['convertGrade'] as const;

export const getConvertGradeMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof convertGrade>>, TError,ConvertGradeMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof convertGrade>>, TError,ConvertGradeMutationVariables, TContext> => {

const mutationKey = getConvertGradeMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof convertGrade>>, ConvertGradeMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  convertGrade(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ConvertGradeMutationResult = NonNullable<Awaited<ReturnType<typeof convertGrade>>>
    export type ConvertGradeMutationBody = BodyType<GradeConversionInput>
    export type ConvertGradeMutationError = ErrorType<unknown>
    export type ConvertGradeMutationVariables = {data: BodyType<GradeConversionInput>}

    /**
 * @summary Convert a grade between common European and global systems
 */
export const useConvertGrade = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof convertGrade>>, TError,ConvertGradeMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof convertGrade>>,
        TError,
        ConvertGradeMutationVariables,
        TContext
      > => {
      return useMutation(getConvertGradeMutationOptions(options));
    }

export const getListBridgeCoursesUrl = (params?: ListBridgeCoursesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/counselor/bridge-courses?${stringifiedParams}` : `/api/counselor/bridge-courses`
}

/**
 * @summary List prerequisite bridge courses
 */
export const listBridgeCourses = async (params?: ListBridgeCoursesParams, options?: Parameters<typeof customFetch>[1]): Promise<BridgeCourse[]> => {

  return customFetch<BridgeCourse[]>(getListBridgeCoursesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListBridgeCoursesQueryKey = (params?: ListBridgeCoursesParams,) => {
    return [
    `/api/counselor/bridge-courses`, ...(params ? [params] : [])
    ] as const;
    }


export const getListBridgeCoursesQueryOptions = <TData = Awaited<ReturnType<typeof listBridgeCourses>>, TError = ErrorType<unknown>>(params?: ListBridgeCoursesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listBridgeCourses>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListBridgeCoursesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listBridgeCourses>>> = ({ signal }) => listBridgeCourses(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listBridgeCourses>>, TError, TData> & { queryKey: QueryKey }
}

export type ListBridgeCoursesQueryResult = NonNullable<Awaited<ReturnType<typeof listBridgeCourses>>>
export type ListBridgeCoursesQueryError = ErrorType<unknown>


/**
 * @summary List prerequisite bridge courses
 */

export function useListBridgeCourses<TData = Awaited<ReturnType<typeof listBridgeCourses>>, TError = ErrorType<unknown>>(
 params?: ListBridgeCoursesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listBridgeCourses>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListBridgeCoursesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetPlannerWorkspaceUrl = () => {




  return `/api/workspace`
}

/**
 * @summary Get the signed-in applicant's planner workspace
 */
export const getPlannerWorkspace = async ( options?: Parameters<typeof customFetch>[1]): Promise<PlannerWorkspace> => {

  return customFetch<PlannerWorkspace>(getGetPlannerWorkspaceUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPlannerWorkspaceQueryKey = () => {
    return [
    `/api/workspace`
    ] as const;
    }


export const getGetPlannerWorkspaceQueryOptions = <TData = Awaited<ReturnType<typeof getPlannerWorkspace>>, TError = ErrorType<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPlannerWorkspace>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlannerWorkspaceQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlannerWorkspace>>> = ({ signal }) => getPlannerWorkspace({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlannerWorkspace>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPlannerWorkspaceQueryResult = NonNullable<Awaited<ReturnType<typeof getPlannerWorkspace>>>
export type GetPlannerWorkspaceQueryError = ErrorType<void>


/**
 * @summary Get the signed-in applicant's planner workspace
 */

export function useGetPlannerWorkspace<TData = Awaited<ReturnType<typeof getPlannerWorkspace>>, TError = ErrorType<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPlannerWorkspace>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPlannerWorkspaceQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getSavePlannerWorkspaceUrl = () => {




  return `/api/workspace`
}

/**
 * @summary Save the signed-in applicant's planner workspace
 */
export const savePlannerWorkspace = async (plannerWorkspaceInput: PlannerWorkspaceInput, options?: Parameters<typeof customFetch>[1]): Promise<PlannerWorkspace> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<PlannerWorkspace>(getSavePlannerWorkspaceUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(plannerWorkspaceInput)
  }
);}





export const getSavePlannerWorkspaceMutationKey = () => ['savePlannerWorkspace'] as const;

export const getSavePlannerWorkspaceMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof savePlannerWorkspace>>, TError,SavePlannerWorkspaceMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof savePlannerWorkspace>>, TError,SavePlannerWorkspaceMutationVariables, TContext> => {

const mutationKey = getSavePlannerWorkspaceMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof savePlannerWorkspace>>, SavePlannerWorkspaceMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  savePlannerWorkspace(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SavePlannerWorkspaceMutationResult = NonNullable<Awaited<ReturnType<typeof savePlannerWorkspace>>>
    export type SavePlannerWorkspaceMutationBody = BodyType<PlannerWorkspaceInput>
    export type SavePlannerWorkspaceMutationError = ErrorType<void>
    export type SavePlannerWorkspaceMutationVariables = {data: BodyType<PlannerWorkspaceInput>}

    /**
 * @summary Save the signed-in applicant's planner workspace
 */
export const useSavePlannerWorkspace = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof savePlannerWorkspace>>, TError,SavePlannerWorkspaceMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof savePlannerWorkspace>>,
        TError,
        SavePlannerWorkspaceMutationVariables,
        TContext
      > => {
      return useMutation(getSavePlannerWorkspaceMutationOptions(options));
    }

