/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
    status: string;
}
export type UniversityTier = typeof UniversityTier[keyof typeof UniversityTier];
export declare const UniversityTier: {
    readonly safe: "safe";
    readonly target: "target";
    readonly reach: "reach";
};
export interface University {
    id: string;
    name: string;
    city: string;
    country: string;
    countryCode: string;
    region: string;
    type: string;
    rank: number;
    tuition: number;
    livingCost: number;
    acceptanceRate: number;
    fitScore: number;
    tier: UniversityTier;
    fields: string[];
    languages: string[];
    applicationUrl: string;
    logo: string;
    image: string;
    highlights: string[];
}
export type StudentProfileInputDegreeLevel = typeof StudentProfileInputDegreeLevel[keyof typeof StudentProfileInputDegreeLevel];
export declare const StudentProfileInputDegreeLevel: {
    readonly 'Bachelor\'s': "Bachelor's";
    readonly 'Master\'s': "Master's";
    readonly PhD: "PhD";
};
export type StudentProfileInputGradeSystem = typeof StudentProfileInputGradeSystem[keyof typeof StudentProfileInputGradeSystem];
export declare const StudentProfileInputGradeSystem: {
    readonly US_GPA: "US GPA";
    readonly UK_Honours: "UK Honours";
    readonly ECTS: "ECTS";
    readonly Bavarian: "Bavarian";
    readonly Percentage: "Percentage";
};
export type StudentProfileInputEnglishTest = typeof StudentProfileInputEnglishTest[keyof typeof StudentProfileInputEnglishTest];
export declare const StudentProfileInputEnglishTest: {
    readonly IELTS: "IELTS";
    readonly TOEFL: "TOEFL";
};
export type StudentProfileInputCurrency = typeof StudentProfileInputCurrency[keyof typeof StudentProfileInputCurrency];
export declare const StudentProfileInputCurrency: {
    readonly EUR: "EUR";
    readonly GBP: "GBP";
    readonly CHF: "CHF";
};
export interface StudentProfileInput {
    degreeLevel: StudentProfileInputDegreeLevel;
    field: string;
    grade: number;
    gradeSystem: StudentProfileInputGradeSystem;
    englishScore: number;
    englishTest?: StudentProfileInputEnglishTest;
    budget: number;
    currency?: StudentProfileInputCurrency;
    experienceYears: number;
    region: string;
    gre?: number;
    prerequisiteTopics?: string[];
}
export interface MatchSummary {
    profileStrength: number;
    totalMatches: number;
    safeCount: number;
    targetCount: number;
    reachCount: number;
    topInsight: string;
}
export interface MatchResponse {
    matches: University[];
    summary: MatchSummary;
}
export type GradeConversionInputFromSystem = typeof GradeConversionInputFromSystem[keyof typeof GradeConversionInputFromSystem];
export declare const GradeConversionInputFromSystem: {
    readonly US_GPA: "US GPA";
    readonly UK_Honours: "UK Honours";
    readonly ECTS: "ECTS";
    readonly Bavarian: "Bavarian";
    readonly Percentage: "Percentage";
};
export type GradeConversionInputToSystem = typeof GradeConversionInputToSystem[keyof typeof GradeConversionInputToSystem];
export declare const GradeConversionInputToSystem: {
    readonly US_GPA: "US GPA";
    readonly UK_Honours: "UK Honours";
    readonly ECTS: "ECTS";
    readonly Bavarian: "Bavarian";
    readonly Percentage: "Percentage";
};
export interface GradeConversionInput {
    value: number;
    fromSystem: GradeConversionInputFromSystem;
    toSystem: GradeConversionInputToSystem;
}
export interface GradeConversion {
    value: number;
    label: string;
    explanation: string;
    scale: string;
}
export interface BridgeCourse {
    id: string;
    title: string;
    provider: string;
    topic: string;
    ects: number;
    duration: string;
    url: string;
    level: string;
}
export interface PlannerWorkspaceInput {
    selectedIds: string[];
    visaTasks: string[];
    auditFiles: string[];
    sopField: string;
    sopInterest: string;
    sopGoal: string;
    resumeText: string;
    ectsTopics: string[];
    syllabusFiles: string[];
}
export type PlannerWorkspace = PlannerWorkspaceInput & {
    updatedAt: string;
};
export type ListUniversitiesParams = {
    search?: string;
    country?: string;
    region?: string;
    degreeLevel?: ListUniversitiesDegreeLevel;
    field?: string;
    maxTuition?: number;
    tier?: ListUniversitiesTier;
    /**
     * @minimum 1
     * @maximum 100
     */
    limit?: number;
};
export type ListUniversitiesDegreeLevel = typeof ListUniversitiesDegreeLevel[keyof typeof ListUniversitiesDegreeLevel];
export declare const ListUniversitiesDegreeLevel: {
    readonly 'Bachelor\'s': "Bachelor's";
    readonly 'Master\'s': "Master's";
    readonly PhD: "PhD";
};
export type ListUniversitiesTier = typeof ListUniversitiesTier[keyof typeof ListUniversitiesTier];
export declare const ListUniversitiesTier: {
    readonly safe: "safe";
    readonly target: "target";
    readonly reach: "reach";
};
export type ListBridgeCoursesParams = {
    topic?: string;
};
//# sourceMappingURL=api.schemas.d.ts.map