export const bridgeCourses = [
  {
    id: "cs-math",
    title: "Mathematics for Computer Science",
    provider: "MIT OpenCourseWare",
    topic: "Advanced Mathematics",
    ects: 6,
    duration: "12 weeks",
    url: "https://ocw.mit.edu/search/?d=Electrical%20Engineering%20and%20Computer%20Science&q=mathematics",
    level: "Intermediate",
  },
  {
    id: "algorithms",
    title: "Algorithms, Part I",
    provider: "Princeton Online",
    topic: "Theoretical CS",
    ects: 5,
    duration: "8 weeks",
    url: "https://www.coursera.org/learn/algorithms-part1",
    level: "Intermediate",
  },
  {
    id: "linear-algebra",
    title: "Linear Algebra for Data Science",
    provider: "Imperial College London",
    topic: "Advanced Mathematics",
    ects: 5,
    duration: "10 weeks",
    url: "https://www.coursera.org/learn/linear-algebra-machine-learning",
    level: "Intermediate",
  },
  {
    id: "systems",
    title: "Computer Systems: A Programmer's Perspective",
    provider: "Carnegie Mellon Open Learning",
    topic: "Systems",
    ects: 6,
    duration: "14 weeks",
    url: "https://www.cs.cmu.edu/~213/",
    level: "Advanced",
  },
  {
    id: "python",
    title: "Programming for Everybody",
    provider: "University of Michigan",
    topic: "Programming",
    ects: 4,
    duration: "6 weeks",
    url: "https://www.coursera.org/learn/python",
    level: "Foundation",
  },
  {
    id: "statistics",
    title: "Statistics with Python",
    provider: "University of Michigan",
    topic: "Statistics",
    ects: 5,
    duration: "10 weeks",
    url: "https://www.coursera.org/specializations/statistics-with-python",
    level: "Intermediate",
  },
];