/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface BridgeCourse {
    id: string;
    title: string;
    provider: string;
    topic: string;
    ects: number;
    duration: string;
    url: string;
    level: string;
}
//# sourceMappingURL=bridgeCourse.d.ts.map