import { useMemo, useState, type ReactNode } from 'react';
import { ArrowRight, BarChart3, BookOpen, Check, ChevronDown, CircleAlert, RefreshCw, ShieldCheck, Sparkles, Target } from 'lucide-react';
import { getListBridgeCoursesQueryKey, useConvertGrade, useListBridgeCourses, useMatchUniversities } from '@workspace/api-client-react';
import type { GradeConversion, StudentProfileInput, University } from '@workspace/api-client-react';
import { UniversityCard } from '@/components/university-card';
import { demoBridgeCourses, demoUniversities } from '@/lib/demo-data';

const defaultProfile: StudentProfileInput = { degreeLevel: "Master's", field: 'Data Science', grade: 3.62, gradeSystem: 'US GPA', englishScore: 7.5, englishTest: 'IELTS', budget: 18000, currency: 'EUR', experienceYears: 2, region: 'Northern Europe', gre: 322, prerequisiteTopics: ['Linear Algebra', 'Statistics'] };
const gradeSystems = ['US GPA', 'UK Honours', 'ECTS', 'Bavarian', 'Percentage'] as const;

export default function Counselor() {
  const [profile, setProfile] = useState<StudentProfileInput>(defaultProfile);
  const [submitted, setSubmitted] = useState<StudentProfileInput>(defaultProfile);
  const [conversion, setConversion] = useState<GradeConversion | null>(null);
  const [conversionValue, setConversionValue] = useState('3.62');
  const [fromSystem, setFromSystem] = useState<typeof gradeSystems[number]>('US GPA');
  const [toSystem, setToSystem] = useState<typeof gradeSystems[number]>('ECTS');
  const [topic, setTopic] = useState('Linear Algebra');
  const match = useMatchUniversities();
  const grade = useConvertGrade();
  const bridgeQuery = useListBridgeCourses({ topic }, { query: { enabled: !!topic, queryKey: getListBridgeCoursesQueryKey({ topic }) } });
  const matches: University[] = match.data?.matches?.length ? match.data.matches : demoUniversities;
  const summary = match.data?.summary || { profileStrength: 78, totalMatches: 12, safeCount: 4, targetCount: 6, reachCount: 2, topInsight: 'Your academic profile is strongest for applied data programmes in Northern and Western Europe.' };
  const bridgeCourses = bridgeQuery.data?.length ? bridgeQuery.data : demoBridgeCourses.filter((course) => course.topic === topic);
  const setNumber = (key: keyof StudentProfileInput, value: string) => setProfile((current) => ({ ...current, [key]: Number(value) }));
  const toggleTopic = (value: string) => setProfile((current) => ({ ...current, prerequisiteTopics: current.prerequisiteTopics?.includes(value) ? current.prerequisiteTopics.filter((topicItem) => topicItem !== value) : [...(current.prerequisiteTopics || []), value] }));
  const runMatch = () => { setSubmitted(profile); match.mutate({ data: profile }); };
  const convert = () => { grade.mutate({ data: { value: Number(conversionValue), fromSystem, toSystem } }, { onSuccess: (result) => setConversion(result) }); };
  const summarySegments = useMemo(() => [{ label: 'Safer', count: summary.safeCount, color: 'bg-emerald-500' }, { label: 'Target', count: summary.targetCount, color: 'bg-accent' }, { label: 'Reach', count: summary.reachCount, color: 'bg-amber-400' }], [summary]);

  return (
    <div className="mx-auto max-w-[1440px] px-5 py-8 md:px-10 md:py-10">
      <section className="rise-in flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-mono-ui text-[10px] uppercase tracking-[0.2em] text-accent">Counselor studio</p><h1 className="mt-3 font-display text-4xl leading-none tracking-[-0.04em] md:text-5xl">Make the shortlist feel earned.</h1><p className="mt-3 max-w-xl text-sm leading-relaxed text-muted-foreground">A transparent read on your fit — not a verdict. Tune the inputs, see the trade-offs, then choose where to spend your attention.</p></div><div className="flex items-center gap-2 text-[11px] text-muted-foreground"><span className="h-2 w-2 rounded-full bg-emerald-500" /> Profile last run a moment ago</div></section>
      <div className="mt-9 grid gap-6 xl:grid-cols-[0.8fr_1.2fr]">
        <section className="rounded-2xl border border-card-border bg-card p-5 shadow-sm md:p-6"><div className="flex items-start justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[0.18em] text-accent">01 · Your inputs</p><h2 className="mt-2 font-display text-2xl">Profile signal</h2></div><div className="grid h-9 w-9 place-items-center rounded-xl bg-secondary text-secondary-foreground"><Target size={17} /></div></div>
          <div className="mt-6 space-y-4">
            <Field label="Degree level"><select value={profile.degreeLevel} onChange={(e) => setProfile({ ...profile, degreeLevel: e.target.value as StudentProfileInput['degreeLevel'] })} className="field-input" data-testid="select-degree-level"><option>Bachelor's</option><option>Master's</option><option>PhD</option></select></Field>
            <Field label="Primary field"><input value={profile.field} onChange={(e) => setProfile({ ...profile, field: e.target.value })} className="field-input" data-testid="input-profile-field" /></Field>
            <div className="grid grid-cols-2 gap-3"><Field label="Grade"><input type="number" step="0.01" value={profile.grade} onChange={(e) => setNumber('grade', e.target.value)} className="field-input" data-testid="input-profile-grade" /></Field><Field label="Grade system"><select value={profile.gradeSystem} onChange={(e) => setProfile({ ...profile, gradeSystem: e.target.value as StudentProfileInput['gradeSystem'] })} className="field-input" data-testid="select-grade-system"><option>US GPA</option><option>UK Honours</option><option>ECTS</option><option>Bavarian</option><option>Percentage</option></select></Field></div>
            <div className="grid grid-cols-2 gap-3"><Field label="English score"><input type="number" step="0.5" value={profile.englishScore} onChange={(e) => setNumber('englishScore', e.target.value)} className="field-input" data-testid="input-english-score" /></Field><Field label="Test"><select value={profile.englishTest} onChange={(e) => setProfile({ ...profile, englishTest: e.target.value as StudentProfileInput['englishTest'] })} className="field-input" data-testid="select-english-test"><option>IELTS</option><option>TOEFL</option></select></Field></div>
            <div className="grid grid-cols-2 gap-3"><Field label="Annual budget (€)"><input type="number" value={profile.budget} onChange={(e) => setNumber('budget', e.target.value)} className="field-input" data-testid="input-budget" /></Field><Field label="Experience (years)"><input type="number" value={profile.experienceYears} onChange={(e) => setNumber('experienceYears', e.target.value)} className="field-input" data-testid="input-experience" /></Field></div>
            <Field label="Preferred region"><select value={profile.region} onChange={(e) => setProfile({ ...profile, region: e.target.value })} className="field-input" data-testid="select-region"><option>Northern Europe</option><option>Western Europe</option><option>Central Europe</option><option>Southern Europe</option><option>Open to all Europe</option></select></Field>
            <div><label className="field-label">Prerequisite topics</label><div className="mt-2 flex flex-wrap gap-2">{['Linear Algebra', 'Statistics', 'Research methods'].map((item) => { const active = profile.prerequisiteTopics?.includes(item); return <button key={item} onClick={() => toggleTopic(item)} className={`rounded-lg border px-2.5 py-2 text-[10px] transition-colors ${active ? 'border-secondary bg-secondary text-secondary-foreground' : 'border-input text-muted-foreground hover:bg-muted'}`} data-testid={`button-topic-${item.toLowerCase().replaceAll(' ', '-')}`}>{active && <Check size={11} className="mr-1 inline" />}{item}</button>; })}</div></div>
          </div>
          <button onClick={runMatch} disabled={match.isPending} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-xs font-semibold text-primary-foreground transition-transform hover:-translate-y-0.5 disabled:cursor-wait disabled:opacity-70" data-testid="button-run-match">{match.isPending ? <RefreshCw size={14} className="animate-spin" /> : <Sparkles size={14} className="text-accent" />}{match.isPending ? 'Recalculating matrix…' : 'Recalculate my fit'}</button>
          {match.isError && <p className="mt-3 text-[11px] leading-relaxed text-amber-800" data-testid="status-match-error">The live matrix is taking a moment. Showing your last profile read while services reconnect.</p>}
        </section>

        <div className="space-y-6">
          <section className="rounded-2xl border border-card-border bg-card p-5 shadow-sm md:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="font-mono-ui text-[10px] uppercase tracking-[0.18em] text-accent">02 · Matrix readout</p><h2 className="mt-2 font-display text-3xl">A balanced map</h2></div><div className="flex items-center gap-3 rounded-xl bg-muted px-3 py-2"><BarChart3 size={17} className="text-accent" /><span className="font-mono-ui text-sm">{summary.profileStrength}<span className="text-muted-foreground">/100</span></span></div></div><div className="mt-7 grid gap-6 md:grid-cols-[1fr_0.9fr]"><div><div className="flex h-3 overflow-hidden rounded-full bg-muted">{summarySegments.map((segment) => <div key={segment.label} className={`${segment.color}`} style={{ width: `${(segment.count / Math.max(summary.totalMatches, 1)) * 100}%` }} />)}</div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2">{summarySegments.map((segment) => <div key={segment.label} className="flex items-center gap-1.5 text-[10px] text-muted-foreground"><span className={`h-2 w-2 rounded-full ${segment.color}`} />{segment.label} <span className="font-mono-ui text-foreground">{segment.count}</span></div>)}</div></div><div className="border-l border-border pl-5 text-sm leading-relaxed text-muted-foreground"><CircleAlert size={16} className="mb-2 text-accent" />{summary.topInsight}</div></div></section>
          <section><div className="mb-4 flex items-end justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[0.18em] text-accent">03 · Recommended first looks</p><h2 className="mt-2 font-display text-2xl">Where to spend time</h2></div><span className="text-[10px] text-muted-foreground">{submitted.field} · {submitted.region}</span></div><div className="grid gap-4 md:grid-cols-2">{matches.slice(0, 4).map((university) => <UniversityCard key={university.id} university={university} compact />)}</div></section>
        </div>
      </div>

      <section className="mt-8 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]">
        <div className="rounded-2xl border border-card-border bg-card p-5 shadow-sm md:p-6"><div className="flex items-start justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[0.18em] text-accent">Grade translator</p><h2 className="mt-2 font-display text-2xl">Make your mark legible.</h2></div><ShieldCheck size={19} className="text-secondary-foreground" /></div><div className="mt-5 grid grid-cols-[0.8fr_1fr] gap-3"><Field label="Your grade"><input type="number" step="0.01" value={conversionValue} onChange={(e) => setConversionValue(e.target.value)} className="field-input" data-testid="input-conversion-value" /></Field><Field label="From"><select value={fromSystem} onChange={(e) => setFromSystem(e.target.value as typeof fromSystem)} className="field-input" data-testid="select-conversion-from">{gradeSystems.map((system) => <option key={system}>{system}</option>)}</select></Field></div><div className="mt-3 grid grid-cols-[1fr_auto] items-end gap-3"><Field label="To"><select value={toSystem} onChange={(e) => setToSystem(e.target.value as typeof toSystem)} className="field-input" data-testid="select-conversion-to">{gradeSystems.map((system) => <option key={system}>{system}</option>)}</select></Field><button onClick={convert} disabled={grade.isPending} className="h-10 rounded-lg bg-secondary px-3 text-[11px] font-semibold text-secondary-foreground disabled:opacity-60" data-testid="button-convert-grade">{grade.isPending ? 'Converting…' : 'Convert'}</button></div>{conversion && <div className="mt-5 rounded-xl bg-muted p-4" data-testid="status-grade-conversion"><div className="flex items-baseline justify-between"><span className="font-display text-3xl">{conversion.value}</span><span className="font-mono-ui text-[10px] uppercase tracking-wider text-muted-foreground">{conversion.scale}</span></div><p className="mt-2 text-xs font-semibold">{conversion.label}</p><p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">{conversion.explanation}</p></div>}</div>
        <div className="rounded-2xl border border-card-border bg-card p-5 shadow-sm md:p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p className="font-mono-ui text-[10px] uppercase tracking-[0.18em] text-accent">Prerequisite bridge</p><h2 className="mt-2 font-display text-2xl">Close the one visible gap.</h2><p className="mt-2 text-xs text-muted-foreground">Short, credit-bearing options to make an application easier to read.</p></div><select value={topic} onChange={(e) => setTopic(e.target.value)} className="field-input sm:w-40" aria-label="Bridge course topic" data-testid="select-bridge-topic"><option>Linear Algebra</option><option>Statistics</option><option>Research methods</option></select></div><div className="mt-5 space-y-2">{bridgeQuery.isLoading ? [1, 2].map((item) => <div key={item} className="skeleton h-16 rounded-xl" />) : bridgeCourses.slice(0, 3).map((course) => <a key={course.id} href={course.url} target="_blank" rel="noreferrer" className="group flex items-center justify-between rounded-xl border border-border/70 p-3 transition-colors hover:bg-muted" data-testid={`link-bridge-course-${course.id}`}><div className="flex min-w-0 items-center gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-secondary text-secondary-foreground"><BookOpen size={15} /></div><div className="min-w-0"><p className="truncate text-xs font-semibold">{course.title}</p><p className="mt-1 text-[10px] text-muted-foreground">{course.provider} · {course.duration} · {course.ects} ECTS</p></div></div><ArrowRight size={15} className="shrink-0 text-muted-foreground transition-transform group-hover:translate-x-1" /></a>)}</div></div>
      </section>
    </div>
  );
}

function Field({ label, children }: { label: string; children: ReactNode }) {
  return <label className="block"><span className="field-label">{label}</span>{children}</label>;
}