import type { BridgeCourse, University } from '@workspace/api-client-react';

export const demoUniversities: University[] = [
  {
    id: 'uva-amsterdam',
    name: 'University of Amsterdam',
    city: 'Amsterdam',
    country: 'Netherlands',
    countryCode: 'NL',
    region: 'Northern Europe',
    type: 'Research university',
    rank: 55,
    tuition: 4200,
    livingCost: 1150,
    acceptanceRate: 38,
    fitScore: 94,
    tier: 'target',
    fields: ['Data Science', 'Computer Science', 'Economics'],
    languages: ['English', 'Dutch'],
    applicationUrl: 'https://www.uva.nl/en/education',
    logo: 'UvA',
    image: '',
    highlights: ['Strong AI research cluster', 'English-taught MSc pathways', 'Central European network'],
  },
  {
    id: 'tue-eindhoven',
    name: 'Eindhoven University of Technology',
    city: 'Eindhoven',
    country: 'Netherlands',
    countryCode: 'NL',
    region: 'Northern Europe',
    type: 'Technical university',
    rank: 99,
    tuition: 14400,
    livingCost: 980,
    acceptanceRate: 42,
    fitScore: 91,
    tier: 'target',
    fields: ['Computer Science', 'Engineering', 'Design'],
    languages: ['English', 'Dutch'],
    applicationUrl: 'https://www.tue.nl/en/education',
    logo: 'TU/e',
    image: '',
    highlights: ['Industry embedded curriculum', 'Design-led engineering', 'High graduate employment'],
  },
  {
    id: 'ku-leuven',
    name: 'KU Leuven',
    city: 'Leuven',
    country: 'Belgium',
    countryCode: 'BE',
    region: 'Western Europe',
    type: 'Research university',
    rank: 63,
    tuition: 3900,
    livingCost: 900,
    acceptanceRate: 31,
    fitScore: 87,
    tier: 'target',
    fields: ['Data Science', 'Business', 'Engineering'],
    languages: ['English', 'Dutch', 'French'],
    applicationUrl: 'https://www.kuleuven.be/english',
    logo: 'KU',
    image: '',
    highlights: ['Low tuition for EU students', 'Historic student city', 'Quantitative methods focus'],
  },
  {
    id: 'eth-zurich',
    name: 'ETH Zürich',
    city: 'Zürich',
    country: 'Switzerland',
    countryCode: 'CH',
    region: 'Central Europe',
    type: 'Technical university',
    rank: 7,
    tuition: 1560,
    livingCost: 1850,
    acceptanceRate: 18,
    fitScore: 78,
    tier: 'reach',
    fields: ['Computer Science', 'Engineering', 'Architecture'],
    languages: ['English', 'German'],
    applicationUrl: 'https://ethz.ch/en/studies.html',
    logo: 'ETH',
    image: '',
    highlights: ['World-leading technical research', 'Exceptional lab access', 'Swiss innovation ecosystem'],
  },
  {
    id: 'aalto-helsinki',
    name: 'Aalto University',
    city: 'Espoo',
    country: 'Finland',
    countryCode: 'FI',
    region: 'Northern Europe',
    type: 'Research university',
    rank: 113,
    tuition: 15000,
    livingCost: 950,
    acceptanceRate: 26,
    fitScore: 84,
    tier: 'target',
    fields: ['Design', 'Business', 'Computer Science'],
    languages: ['English', 'Finnish', 'Swedish'],
    applicationUrl: 'https://www.aalto.fi/en/study-options',
    logo: 'A!',
    image: '',
    highlights: ['Cross-school degrees', 'Nordic design culture', 'Startup-friendly campus'],
  },
  {
    id: 'polimi-milan',
    name: 'Politecnico di Milano',
    city: 'Milan',
    country: 'Italy',
    countryCode: 'IT',
    region: 'Southern Europe',
    type: 'Technical university',
    rank: 123,
    tuition: 3900,
    livingCost: 1050,
    acceptanceRate: 48,
    fitScore: 88,
    tier: 'safe',
    fields: ['Engineering', 'Architecture', 'Design'],
    languages: ['English', 'Italian'],
    applicationUrl: 'https://www.polimi.it/en/prospective-students',
    logo: 'POLI',
    image: '',
    highlights: ['Excellent design reputation', 'Flexible fee bands', 'Milan industry access'],
  },
];

export const demoBridgeCourses: BridgeCourse[] = [
  {
    id: 'linear-algebra',
    title: 'Linear Algebra for Data Science',
    provider: 'DelftX',
    topic: 'Linear Algebra',
    ects: 5,
    duration: '8 weeks',
    url: 'https://online-learning.tudelft.nl/',
    level: 'Intermediate',
  },
  {
    id: 'python-statistics',
    title: 'Statistical Programming with Python',
    provider: 'University of Helsinki',
    topic: 'Statistics',
    ects: 4,
    duration: '6 weeks',
    url: 'https://www.helsinki.fi/en',
    level: 'Foundation',
  },
  {
    id: 'research-methods',
    title: 'Research Methods & Academic Writing',
    provider: 'KU Leuven',
    topic: 'Research methods',
    ects: 3,
    duration: '5 weeks',
    url: 'https://www.kuleuven.be/english',
    level: 'Foundation',
  },
];