/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type GradeConversionInputFromSystem = typeof GradeConversionInputFromSystem[keyof typeof GradeConversionInputFromSystem];
export declare const GradeConversionInputFromSystem: {
    readonly US_GPA: "US GPA";
    readonly UK_Honours: "UK Honours";
    readonly ECTS: "ECTS";
    readonly Bavarian: "Bavarian";
    readonly Percentage: "Percentage";
};
//# sourceMappingURL=gradeConversionInputFromSystem.d.ts.map