/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type GradeConversionInputToSystem = typeof GradeConversionInputToSystem[keyof typeof GradeConversionInputToSystem];
export declare const GradeConversionInputToSystem: {
    readonly US_GPA: "US GPA";
    readonly UK_Honours: "UK Honours";
    readonly ECTS: "ECTS";
    readonly Bavarian: "Bavarian";
    readonly Percentage: "Percentage";
};
//# sourceMappingURL=gradeConversionInputToSystem.d.ts.map