/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface GradeConversion {
    value: number;
    label: string;
    explanation: string;
    scale: string;
}
//# sourceMappingURL=gradeConversion.d.ts.map