/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { GradeConversionInputFromSystem } from './gradeConversionInputFromSystem';
import type { GradeConversionInputToSystem } from './gradeConversionInputToSystem';
export interface GradeConversionInput {
    value: number;
    fromSystem: GradeConversionInputFromSystem;
    toSystem: GradeConversionInputToSystem;
}
//# sourceMappingURL=gradeConversionInput.d.ts.map