/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type GradeConversionInputFromSystem = typeof GradeConversionInputFromSystem[keyof typeof GradeConversionInputFromSystem];


export const GradeConversionInputFromSystem = {
  US_GPA: 'US GPA',
  UK_Honours: 'UK Honours',
  ECTS: 'ECTS',
  Bavarian: 'Bavarian',
  Percentage: 'Percentage',
} as const;
