/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type ListUniversitiesTier = typeof ListUniversitiesTier[keyof typeof ListUniversitiesTier];


export const ListUniversitiesTier = {
  safe: 'safe',
  target: 'target',
  reach: 'reach',
} as const;
