/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { ListUniversitiesDegreeLevel } from './listUniversitiesDegreeLevel';
import type { ListUniversitiesTier } from './listUniversitiesTier';

export type ListUniversitiesParams = {
search?: string;
country?: string;
region?: string;
degreeLevel?: ListUniversitiesDegreeLevel;
field?: string;
maxTuition?: number;
tier?: ListUniversitiesTier;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
