/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type ListUniversitiesDegreeLevel = typeof ListUniversitiesDegreeLevel[keyof typeof ListUniversitiesDegreeLevel];
export declare const ListUniversitiesDegreeLevel: {
    readonly 'Bachelor\'s': "Bachelor's";
    readonly 'Master\'s': "Master's";
    readonly PhD: "PhD";
};
//# sourceMappingURL=listUniversitiesDegreeLevel.d.ts.map