/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type ListUniversitiesTier = typeof ListUniversitiesTier[keyof typeof ListUniversitiesTier];
export declare const ListUniversitiesTier: {
    readonly safe: "safe";
    readonly target: "target";
    readonly reach: "reach";
};
//# sourceMappingURL=listUniversitiesTier.d.ts.map