/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type ListUniversitiesDegreeLevel = typeof ListUniversitiesDegreeLevel[keyof typeof ListUniversitiesDegreeLevel];


export const ListUniversitiesDegreeLevel = {
  'Bachelor\'s': 'Bachelor\'s',
  'Master\'s': 'Master\'s',
  PhD: 'PhD',
} as const;
