/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { MatchSummary } from './matchSummary';
import type { University } from './university';

export interface MatchResponse {
  matches: University[];
  summary: MatchSummary;
}
