/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface MatchSummary {
  profileStrength: number;
  totalMatches: number;
  safeCount: number;
  targetCount: number;
  reachCount: number;
  topInsight: string;
}
