/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { PlannerWorkspaceInput } from './plannerWorkspaceInput';
export type PlannerWorkspace = PlannerWorkspaceInput & {
    updatedAt: Date;
};
//# sourceMappingURL=plannerWorkspace.d.ts.map