/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { StudentProfileInputCurrency } from './studentProfileInputCurrency';
import type { StudentProfileInputDegreeLevel } from './studentProfileInputDegreeLevel';
import type { StudentProfileInputEnglishTest } from './studentProfileInputEnglishTest';
import type { StudentProfileInputGradeSystem } from './studentProfileInputGradeSystem';

export interface StudentProfileInput {
  degreeLevel: StudentProfileInputDegreeLevel;
  field: string;
  grade: number;
  gradeSystem: StudentProfileInputGradeSystem;
  englishScore: number;
  englishTest?: StudentProfileInputEnglishTest;
  budget: number;
  currency?: StudentProfileInputCurrency;
  experienceYears: number;
  region: string;
  gre?: number;
  prerequisiteTopics?: string[];
}
