/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type StudentProfileInputDegreeLevel = typeof StudentProfileInputDegreeLevel[keyof typeof StudentProfileInputDegreeLevel];


export const StudentProfileInputDegreeLevel = {
  'Bachelor\'s': 'Bachelor\'s',
  'Master\'s': 'Master\'s',
  PhD: 'PhD',
} as const;
