/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type StudentProfileInputDegreeLevel = typeof StudentProfileInputDegreeLevel[keyof typeof StudentProfileInputDegreeLevel];
export declare const StudentProfileInputDegreeLevel: {
    readonly 'Bachelor\'s': "Bachelor's";
    readonly 'Master\'s': "Master's";
    readonly PhD: "PhD";
};
//# sourceMappingURL=studentProfileInputDegreeLevel.d.ts.map