/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type StudentProfileInputCurrency = typeof StudentProfileInputCurrency[keyof typeof StudentProfileInputCurrency];
export declare const StudentProfileInputCurrency: {
    readonly EUR: "EUR";
    readonly GBP: "GBP";
    readonly CHF: "CHF";
};
//# sourceMappingURL=studentProfileInputCurrency.d.ts.map