/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type StudentProfileInputCurrency = typeof StudentProfileInputCurrency[keyof typeof StudentProfileInputCurrency];


export const StudentProfileInputCurrency = {
  EUR: 'EUR',
  GBP: 'GBP',
  CHF: 'CHF',
} as const;
