/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type StudentProfileInputEnglishTest = typeof StudentProfileInputEnglishTest[keyof typeof StudentProfileInputEnglishTest];


export const StudentProfileInputEnglishTest = {
  IELTS: 'IELTS',
  TOEFL: 'TOEFL',
} as const;
