/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type UniversityTier = typeof UniversityTier[keyof typeof UniversityTier];


export const UniversityTier = {
  safe: 'safe',
  target: 'target',
  reach: 'reach',
} as const;
