/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { UniversityTier } from './universityTier';

export interface University {
  id: string;
  name: string;
  city: string;
  country: string;
  countryCode: string;
  region: string;
  type: string;
  rank: number;
  tuition: number;
  livingCost: number;
  acceptanceRate: number;
  fitScore: number;
  tier: UniversityTier;
  fields: string[];
  languages: string[];
  applicationUrl: string;
  logo: string;
  image: string;
  highlights: string[];
}
